valor1 = input("Por favor, digite o primeiro valor: ")
valor2 = input("Por favor, digite o segundo valor: ")
soma = float(valor1) + float(valor2)
print("A soma entre os valores é {}".format(soma))
subtração = float(valor1) - float(valor2)
print("A subtração entre os valores é {}".format(subtração))
divisão = float(valor1) / float(valor2)
print("A divisão entre os valores é {}".format(divisão))
multiplicação = float(valor1) * float(valor2)
print("A multiplicação entre os valores é {}".format(multiplicação))
